finished 04-skeleton
js-tasks-ru/htmlcss-20220519_vitalijs-maslobojevs92 pull request #11
Opened 2022-05-30 14:35 UTC by Inkq

2022-05-30 14:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-30 15:32 UTC, GSemikozov requested changes

2022-05-30 15:32 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 580px;
ширину не стоит ограничивать

2022-05-30 15:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-31 12:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-31 12:46 UTC, Inkq commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 580px;
Убрал ширину у блока. Добавил внешний контейнер с такой шириной, для соответствия с макетом.

2022-05-31 13:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-31 13:29 UTC, GSemikozov approved these changes

2022-05-31 13:30 UTC, merged