finished 05-calendar
js-tasks-ru/htmlcss-20220519_vitalijs-maslobojevs92 pull request #13
Opened 2022-06-01 13:33 UTC by Inkq

Вроде сделал всё как вы показывали с резиновым контейнером. Но шрифт как у вас всё-равно автоматически не уменьшается.

2022-06-01 13:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-02 15:49 UTC, GSemikozov requested changes

2022-06-02 15:49 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  width: 300px;
можно оставить max-width

2022-06-03 12:03 UTC, Inkq commented on 05-lection3/03-calendar/calendar.css
> +  width: 300px;
убрал width

2022-06-05 10:55 UTC, GSemikozov approved these changes

2022-06-05 10:56 UTC, merged