finished 05-modal task
js-tasks-ru/htmlcss-20220519_vitalijs-maslobojevs92 pull request #15
Opened 2022-06-02 13:47 UTC by Inkq

2022-06-02 13:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-02 15:51 UTC, GSemikozov requested changes

2022-06-02 15:51 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal-window__overlay {
сам по себе элемент лишний, скрывать / показывать будем именно весь блок .modal, поэтому стили нужно перенести туда

2022-06-02 15:51 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +          <p class="modal-window__title">Modal title</p>
если это заголовок, то скорее всего что-то от h3 до h6

2022-06-03 12:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-03 12:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-03 12:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-05 18:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-05 18:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-09 10:50 UTC, Inkq commented on 05-lection3/02-modal/modal.css
> +.modal-window__overlay {
исправил

2022-06-09 10:50 UTC, Inkq commented on 05-lection3/02-modal/index.html
> +          <p class="modal-window__title">Modal title</p>
исправил

2022-06-09 15:25 UTC, GSemikozov submitted a review, later dismissed

2022-06-09 15:25 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-06-13 14:46 UTC, GSemikozov approved these changes

2022-06-13 14:46 UTC, merged