07 radio
js-tasks-ru/htmlcss-20220519_vitalijs-maslobojevs92 pull request #21
Opened 2022-06-08 18:31 UTC by Inkq

2022-06-08 18:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-08 18:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-09 15:30 UTC, GSemikozov requested changes

2022-06-09 15:30 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio__input {
здесь то же самое что и в ПР по чекбоксу

2022-06-09 15:30 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  background: url('public/radio.svg');
в принципе можно обойтись без лишний иконок и отрисовать через css

2022-06-09 18:20 UTC, Inkq commented on 07-lection5/02-radio/radio.css
> +  background: url('public/radio.svg');
пробовал отрисовать с помощью css:
![controls](https://user-images.githubusercontent.com/18406621/172916833-fa18d332-d62b-40e1-b083-85d193b6a4f9.png)
При разных масштабах точка смещается.

2022-06-09 19:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-09 19:49 UTC, Inkq commented on 07-lection5/02-radio/radio.css
> +  background: url('public/radio.svg');
Переписал на чистом css. При масштабе 100% точка стоит ровно. А если сделать 90% то она сьезжает.

2022-06-09 19:51 UTC, Inkq commented on 07-lection5/02-radio/radio.css
> +.radio__input {
исправил

2022-06-09 19:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-09 19:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-13 14:48 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  background: url('public/radio.svg');
оставляем такой вариант

2022-06-13 14:49 UTC, GSemikozov approved these changes

2022-06-13 14:49 UTC, merged