finished 01-button task
js-tasks-ru/htmlcss-20220519_vitalijs-maslobojevs92 pull request #6
Opened 2022-05-24 20:52 UTC by Inkq

2022-05-24 20:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-26 14:39 UTC, GSemikozov requested changes

2022-05-26 14:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
ширину лучше жестко не фиксировать, можно убрать

2022-05-26 14:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 0;
а тут наоборот лучше задать как в дизайне

2022-05-26 14:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  border: none;
не хватает box-sizing: border-box

2022-05-26 18:04 UTC, Inkq commented
На время закрою. Нужно ввети правки.

2022-05-27 13:19 UTC, Inkq commented
Убрал фиксированную ширину у кнопки. Добавил общие стили страницы в body.

2022-05-27 18:30 UTC, GSemikozov requested changes

2022-05-27 18:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 0 66.5px;
15px 15px 14px

2022-05-27 18:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  border: none;
до сих пор актуально

2022-05-27 20:05 UTC, Inkq commented on 03-lection1/01-button/button.css
> +  border: none;
В main.css прописан  box-sizing: border-box;

`html {
  box-sizing: border-box;
  font-size: 100%;
}

*,
*::before,
*::after {
  box-sizing: inherit;
}`

2022-05-27 20:27 UTC, Inkq commented on 03-lection1/01-button/button.css
> +  padding: 0 66.5px;
В таком случае кнопка получается слишком узкой и не соответсвует размерам макета. Это приемлемо?
![изображение](https://user-images.githubusercontent.com/18406621/170784665-217dab02-b86a-4145-a805-93ed8f1d2f36.png)

2022-05-27 21:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-28 11:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 0 66.5px;
это ок, поскольку, повторюсь, сетка в макете по который выстроены кнопки - используется только  для более наглядной иллюстрации типов и состояний

2022-05-28 11:23 UTC, GSemikozov approved these changes

2022-05-28 11:23 UTC, merged